apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
  labels:
    app: employee
spec:
  selector:
    matchLabels:
      app: employee
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
