apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: db
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: db-deployment
        image: <image-name>:<tag>
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credentials
                key: password
        ports:
          - containerPort: 3306
      dnsPolicy: ClusterFirst
      restartPolicy: Always
