apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        appdb: mysql
    spec:
      containers:
      - name: db-deployment
        image: docker.io/library/my-db:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        ports:
        - containerPort: 3306
      dnsPolicy: ClusterFirst
      restartPolicy: Always
