apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: db
  labels:
    appdb: mysql
spec:  
  containers:
  - name: db
    image: docker.io/library/mysql:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-credentials
          key: password
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
      - mountPath: "/var/lib/mysql"
        subPath: "mysql"
        name: mysql-data
    volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-disk

