apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: db
  labels:
    manifestType: pod
spec:
  containers:
  - name: db
    image: <image-name>:<tag>
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: password
    ports:
    - containerPort: 3306
  dnsPolicy: ClusterFirst
  restartPolicy: Always