apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: db
  labels:
    appdb: mysql
spec:  
  containers:
  - name: db
    image: docker.io/library/mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: password
      - name: MYSQL_DATABASE
        value: employees
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-credentials
            key: password
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: mysql-initdb
        mountPath: /docker-entrypoint-initdb.d
      - mountPath: "/var/lib/mysql"
        name: mysql-data
  volumes:
    - name: mysql-initdb
      configMap:
        name: mysql-config
    - name: mysql-data
      persistentVolumeClaim:
        claimName: mysql-data-disk
  dnsPolicy: ClusterFirst
  restartPolicy: Always
